from tkinter import *
from PIL import ImageTk,Image
screen=Tk()
screen.title("Registration Enquiry")
screen.geometry("500x450")
img = Image.open("C:/Users/asus/Downloads/00.jpg")
img = img.resize((100,50))
my = ImageTk.PhotoImage(img)
label=Label(screen,image=my).place(x=240,y=50)
screen.resizable(False,False)
def Submit():
    name=name_info.get()
    age=age_info.get()
    phone=phone_info.get()
    Address=Address_info.get()
    email=email_info.get()
    with open(name+".txt","w")as f:
        f.write(name+"\n")
        f.write(age+"\n")
        f.write(phone+"\n")
        f.write(Address+"\n")
        f.write(email+"\n")
def Clear():
    Name_Entry.delete(0,END)
    Age_Entry.delete(0, END)
    PHONE_Entry.delete(0,END)
    Email_Entry.delete(0,END)
    Address_Entry.delete(0,END)
Label(screen,text="Registration Form",font="ariel 20 bold",bg="yellow",fg="black").pack(fill="both")
Label(screen,text="Please Fill The Form Correctly With Valid Details",font=20,bg="blue",fg="white").place(x=100,y=40)
Label(screen,text="Name",font=20).place(x=100,y=70+40)
Label(screen,text="Age",font=20).place(x=100,y=110+40)
Label(screen,text="Select your Gender",font=20).place(x=100,y=150+40)
Label(screen,text="Phone No.",font=20).place(x=100,y=190+40)
Label(screen,text="Email Id",font=20).place(x=100,y=230+40)
Label(screen,text="Course",font=20).place(x=100,y=270+40)
Label(screen,text="Address",font=20).place(x=100,y=310+40)
#Entry
name_info = StringVar()
age_info = StringVar()
phone_info = StringVar()
Address_info = StringVar()
email_info=StringVar()

Name_Entry=Entry(screen,width= 30,font="5",bd=6,textvariable=name_info)
Name_Entry.place(x= 180,y=70+40)
Age_Entry=Entry(screen,width=3,font="5",bd=6,textvariable=age_info)
Age_Entry.place(x= 180,y=110+40)
gender = StringVar()
Gender_Entry=Radiobutton(screen, text="Male", variable = gender,value="Male",font="15")
Gender_Entry.place(x=240,y=190)
Gender2_Entry=Radiobutton(screen, text="Female", variable = gender,value="Female",font="15")
Gender2_Entry.place(x=340,y=190)
PHONE_Entry=Entry(screen,width=15,font="5",bd=6,textvariable=phone_info)
PHONE_Entry.place(x= 180,y=190+40)
Email_Entry=Entry(screen,width=25,font="5",bd=6,textvariable=email_info)
Email_Entry.place(x= 180,y=230+40)
list=["Technical","Non-Technical"]
listcourse=StringVar(screen)
listcourse.set("Select Course")
menu=OptionMenu(screen,listcourse,*list).place(x=180,y=270+40)
Address_Entry=Entry(screen,width=30,font="5",bd=6,textvariable=Address_info)
Address_Entry.place(x= 180,y=310+40)
Button(screen,text="Submit",font="ariel 10 bold",command=Submit,bd=6,bg="red",fg="white").place(x=220,y=400)
Button(screen,text="Clear",font="ariel 10 bold",command=Clear,bd=6,bg="green",fg="white").place(x=430,y=410)
mainloop()